### ISSUE TITLE
How do i edit the readme.md file using Git GUI?

### ISSUE THREAD

**Issue by reagir007** [dcmiddle/sandbox#4]
Is that a problem, i dont need to deal with as i should just use the browser? The first step of the instructions was to download git, so i did and tried to use it. Could i have done what i did (update the readme.MD file) without installing git? Please help!

**Comment by dcmiddle** [comment]
You can get by with the web UI for some things and that might be totally fine for uses like editing a readme.
The web UI can be limited though. I've seen it become difficult when people have not signed off a commit (a topic I didn't get into in the readme). If you need to then amend the commit I don't know if the UI supports that. 
Also in general usage commits may involve multiple files and PRs include multiple commits. I'm not sure if that kind of usage is supported in the UI.

**Comment by reagir007** [comment]
@dcmiddle thanks ... i couldnt figure out how to make changes with Git GUI and commit my changes. I would love to understand that.
